final products = [
  {
    'id': '0',
    'title': 'Air Force 1 Grey White Sneaker for Men',
    'price': 1325,
    'sizes': [8, 9, 10, 11],
    'imageUrl': 'assets/image/shoes_2.png',
    'company': 'sneaker',
  },
  {
    'id': '1',
    'title': 'Best goldstar shoes for men',
    'price': 1000,
    'sizes': [8, 9, 10, 11],
    'imageUrl': 'assets/image/goldstar.png',
    'company': 'goldstar',
  },
  {
    'id': '2',
    'title': 'Nike shoes for men',
    'price': 2500,
    'sizes': [8, 9, 10, 11],
    'imageUrl': 'assets/image/shoes5.png',
    'company': 'nike',
  },
  {
    'id': '3',
    'title': 'Air Force 1 Grey White Bata for Men',
    'price': 1348,
    'sizes': [8, 9, 10, 11],
    'imageUrl': 'assets/image/shoes_3.png',
    'company': 'bata',
  },
  {
    'id': '4',
    'title': 'Addidas shoe for Men',
    'price': 1348,
    'sizes': [8, 9, 10, 11],
    'imageUrl': 'assets/image/shoes_4.png',
    'company': 'addidas',
  },
];
